#!/usr/bin/env bash
#
# RentWise — one-command bootstrap.
#
#   ./start.sh            Development: hot reload, source bind-mounted (default)
#   ./start.sh prod       Production:  nginx serves a built bundle
#   ./start.sh --clean    Wipe the database volume first (DESTRUCTIVE, prompts)
#   ./start.sh --stop     Stop everything and exit
#   ./start.sh --logs     Tail logs of the running stack
#
# Tears down any existing RentWise containers, recreates them, waits until each
# service is genuinely answering, then prints the URLs.

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

BOLD=$'\033[1m'; DIM=$'\033[2m'; RED=$'\033[31m'; GREEN=$'\033[32m'
YELLOW=$'\033[33m'; BLUE=$'\033[34m'; RESET=$'\033[0m'

step()  { printf '\n%s==>%s %s%s%s\n' "$BLUE" "$RESET" "$BOLD" "$1" "$RESET"; }
ok()    { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }
warn()  { printf '  %s!%s %s\n' "$YELLOW" "$RESET" "$1"; }
die()   { printf '\n%serror:%s %s\n\n' "$RED" "$RESET" "$1" >&2; exit 1; }

MODE="dev"
CLEAN=false
ACTION="up"

for arg in "$@"; do
  case "$arg" in
    dev|--dev)       MODE="dev" ;;
    prod|--prod)     MODE="prod" ;;
    --clean)         CLEAN=true ;;
    --stop|--down)   ACTION="stop" ;;
    --logs)          ACTION="logs" ;;
    -h|--help)
      # Print the header comment block, stopping at the first line of code.
      awk 'NR>1 { if ($0 !~ /^#/) exit; sub(/^# ?/, ""); print }' "${BASH_SOURCE[0]}"
      exit 0 ;;
    *) die "unknown option '$arg' (try --help)" ;;
  esac
done

if [ "$MODE" = "dev" ]; then
  COMPOSE=(docker compose -f docker-compose.yml -f docker-compose.dev.yml)
else
  COMPOSE=(docker compose -f docker-compose.yml)
fi

# ---------------------------------------------------------------- prerequisites
step "Checking prerequisites"

command -v docker >/dev/null 2>&1 || die "Docker is not installed. Get it from https://docker.com"

if ! docker info >/dev/null 2>&1; then
  warn "Docker daemon is not running — starting Docker Desktop..."
  if [ "$(uname)" = "Darwin" ]; then
    open -a Docker 2>/dev/null || die "Could not launch Docker Desktop. Start it manually."
  else
    die "Start the Docker daemon, then re-run this script."
  fi

  printf '  waiting for Docker'
  for _ in $(seq 1 90); do
    docker info >/dev/null 2>&1 && break
    printf '.'; sleep 2
  done
  printf '\n'
  docker info >/dev/null 2>&1 || die "Docker did not start in time."
fi
ok "Docker $(docker version --format '{{.Server.Version}}' 2>/dev/null || echo 'ready')"

docker compose version >/dev/null 2>&1 || die "The 'docker compose' plugin is missing."
ok "Compose plugin present"

# ------------------------------------------------------------- early exit paths
if [ "$ACTION" = "logs" ]; then
  exec "${COMPOSE[@]}" logs -f
fi

if [ "$ACTION" = "stop" ]; then
  step "Stopping RentWise"
  "${COMPOSE[@]}" down
  ok "Stopped. Database volume kept — use --clean to wipe it."
  exit 0
fi

# ------------------------------------------------------------------ environment
step "Checking environment"

if [ ! -f .env ]; then
  warn ".env not found — generating one with fresh secrets"

  if ! command -v openssl >/dev/null 2>&1; then
    die "openssl is required to generate secrets. Install it, or copy .env.example to .env and fill it in by hand."
  fi

  cat > .env <<EOF
# Generated by start.sh on $(date). Never commit this file.
POSTGRES_USER=rentwise
POSTGRES_PASSWORD=$(openssl rand -hex 16)
POSTGRES_DB=rentwise

JWT_ACCESS_SECRET=$(openssl rand -base64 48 | tr -d '\n')
JWT_REFRESH_SECRET=$(openssl rand -base64 48 | tr -d '\n')
JWT_ACCESS_TTL=15m
REFRESH_TTL_DAYS=30

NODE_ENV=development
CORS_ORIGIN=http://localhost:3000,http://localhost:8080
COOKIE_DOMAIN=localhost

# Host ports. Change these if something else already uses them.
HTTP_PORT=8080
API_PORT=4000
WEB_PORT=3000
POSTGRES_PORT=5432
EOF
  chmod 600 .env
  ok "Wrote .env with freshly generated secrets"
else
  ok ".env already present — leaving it alone"
fi

# Load it so the port checks below use the real values.
set -a; . ./.env; set +a

# ------------------------------------------------------------------ port checks
step "Checking ports"

port_busy() { lsof -nP -iTCP:"$1" -sTCP:LISTEN >/dev/null 2>&1; }

if [ "$MODE" = "dev" ]; then
  WANTED=("${WEB_PORT:-3000}:web" "${API_PORT:-4000}:api" "${POSTGRES_PORT:-5432}:postgres")
else
  WANTED=("${HTTP_PORT:-8080}:nginx")
fi

# Ports held by our own containers are fine — they are about to be recreated.
OURS=$("${COMPOSE[@]}" ps -q 2>/dev/null | wc -l | tr -d ' ')

for entry in "${WANTED[@]}"; do
  p="${entry%%:*}"; svc="${entry##*:}"
  if port_busy "$p" && [ "$OURS" = "0" ]; then
    warn "port $p ($svc) is in use by something else — change ${svc^^}_PORT in .env if startup fails"
  fi
done
ok "Port check done"

# --------------------------------------------------------------------- teardown
step "Removing any existing RentWise containers"

# COMPOSE_PROFILES=full brings profile-gated services (the prod nginx) into
# scope, so switching between dev and prod does not leave a stale container
# from the other mode still bound to its port.
if [ "$CLEAN" = true ]; then
  printf '  %sThis deletes the database volume and every saved account and scenario.%s\n' "$YELLOW" "$RESET"
  read -r -p "  Type 'yes' to confirm: " reply
  if [ "$reply" = "yes" ]; then
    COMPOSE_PROFILES=full "${COMPOSE[@]}" down -v --remove-orphans
    ok "Containers and database volume removed"
  else
    warn "Skipped the wipe — keeping your data"
    COMPOSE_PROFILES=full "${COMPOSE[@]}" down --remove-orphans
    ok "Containers removed, database kept"
  fi
else
  COMPOSE_PROFILES=full "${COMPOSE[@]}" down --remove-orphans
  ok "Containers removed, database volume kept"
fi

# ------------------------------------------------------------------------ build
step "Building images ($MODE)"
printf '  %sfirst run pulls base images and installs dependencies — expect a few minutes%s\n' "$DIM" "$RESET"
"${COMPOSE[@]}" build
ok "Images built"

# ------------------------------------------------------------------------ start
step "Starting services"
"${COMPOSE[@]}" up -d
ok "Containers started"

# Migrations run automatically: the production entrypoint applies them before
# serving, and the dev overlay applies them before starting the watcher.

wait_for() { # url label timeout
  local url="$1" label="$2" timeout="${3:-120}" i=0
  printf '  waiting for %s' "$label"
  while [ "$i" -lt "$timeout" ]; do
    if curl -sf "$url" >/dev/null 2>&1; then printf ' %s✓%s\n' "$GREEN" "$RESET"; return 0; fi
    printf '.'; sleep 2; i=$((i + 2))
  done
  printf ' %s✗%s\n' "$RED" "$RESET"
  return 1
}

step "Waiting for services to answer"

API_URL="http://localhost:${API_PORT:-4000}/api/health"
[ "$MODE" = "prod" ] && API_URL="http://localhost:${HTTP_PORT:-8080}/api/health"

if ! wait_for "$API_URL" "api" 180; then
  printf '\n%sThe API did not come up. Last 40 log lines:%s\n\n' "$RED" "$RESET"
  "${COMPOSE[@]}" logs --tail=40 api
  die "Startup failed. Fix the error above, then re-run ./start.sh"
fi

if [ "$MODE" = "dev" ]; then
  wait_for "http://localhost:${WEB_PORT:-3000}/" "web" 120 \
    || warn "Vite is still starting — give it a moment and refresh"
else
  wait_for "http://localhost:${HTTP_PORT:-8080}/healthz" "nginx" 120 \
    || warn "nginx is still starting"
fi

# ----------------------------------------------------------------------- report
step "Status"
"${COMPOSE[@]}" ps --format "table {{.Service}}\t{{.Status}}\t{{.Ports}}" 2>/dev/null || "${COMPOSE[@]}" ps

printf '\n%s────────────────────────────────────────────────────────%s\n' "$GREEN" "$RESET"
printf '%s  RentWise is running (%s)%s\n' "$BOLD" "$MODE" "$RESET"
printf '%s────────────────────────────────────────────────────────%s\n\n' "$GREEN" "$RESET"

if [ "$MODE" = "dev" ]; then
  printf '  App          %shttp://localhost:%s%s\n' "$BOLD" "${WEB_PORT:-3000}" "$RESET"
  printf '  API          http://localhost:%s/api\n' "${API_PORT:-4000}"
  printf '  API docs     http://localhost:%s/api/docs\n' "${API_PORT:-4000}"
  printf '  Database     localhost:%s\n\n' "${POSTGRES_PORT:-5432}"
  printf '  %sEdit anything under apps/ or packages/ — it reloads automatically.%s\n' "$DIM" "$RESET"
  printf '  %sNo rebuild needed unless you change dependencies.%s\n\n' "$DIM" "$RESET"
else
  printf '  App          %shttp://localhost:%s%s\n' "$BOLD" "${HTTP_PORT:-8080}" "$RESET"
  printf '  API          http://localhost:%s/api\n\n' "${HTTP_PORT:-8080}"
fi

printf '  Logs         ./start.sh --logs\n'
printf '  Stop         ./start.sh --stop\n'
printf '  Reset data   ./start.sh --clean\n\n'
