import React, { useState } from 'react';
import { X, Copy, Check, Share2 } from 'lucide-react';
import { CalculationResults, CalculatorInputs, Currency, formatCurrency, formatPercent } from '@rentwise/shared';

interface ShareModalProps {
  isOpen: boolean;
  onClose: () => void;
  results: CalculationResults;
  inputs: CalculatorInputs;
  currency: Currency;
}

export const ShareModal: React.FC<ShareModalProps> = ({
  isOpen,
  onClose,
  results,
  inputs,
  currency,
}) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const summaryText = `🏠 RentWise Housing Summary
━━━━━━━━━━━━━━━━━━━━
💰 Total Monthly Housing: ${formatCurrency(results.totalHousingCost, currency)}
• Base Rent: ${formatCurrency(results.totalRent, currency)}
• Utilities: ${formatCurrency(results.totalUtilities, currency)}

👥 Occupants: ${results.peopleCount} People (You + ${inputs.roommates} Roommate${inputs.roommates === 1 ? '' : 's'})
✨ Fair Per Person Share: ${formatCurrency(results.perPersonCost, currency)} / month
📅 Annual Per Person: ${formatCurrency(results.annualPerPersonCost, currency)} / year

📊 Affordability Verdict: ${results.statusTitle}
• Housing % of Income: ${formatPercent(results.housingPercentage, 1)} (Target: ${inputs.affordabilityTarget}%)
• Max Affordable Rent: ${results.isMaxRentNegative ? formatCurrency(0, currency) : formatCurrency(results.maxAffordableRent, currency)}

Generated by RentWise 🚀`;

  const handleCopy = () => {
    navigator.clipboard.writeText(summaryText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs animate-in fade-in duration-200">
      <div
        className="bg-white rounded-3xl max-w-lg w-full p-6 sm:p-8 shadow-2xl border border-slate-100 relative animate-in zoom-in-95 duration-150"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Close Button */}
        <button
          type="button"
          onClick={onClose}
          className="absolute top-5 right-5 p-2 text-slate-400 hover:text-slate-700 hover:bg-slate-100 rounded-full transition-colors"
          aria-label="Close modal"
        >
          <X className="w-5 h-5" />
        </button>

        {/* Modal Header */}
        <div className="flex items-center gap-3 mb-5">
          <div className="w-10 h-10 rounded-2xl bg-brand-50 text-brand-600 flex items-center justify-center">
            <Share2 className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-lg font-bold text-slate-900">
              Share Split Summary
            </h3>
            <p className="text-xs text-slate-500">
              Ready to send to roommates or save for your records
            </p>
          </div>
        </div>

        {/* Text Preview Box */}
        <div className="bg-slate-50 p-4 rounded-2xl border border-slate-200 text-xs font-mono text-slate-800 whitespace-pre-wrap leading-relaxed max-h-72 overflow-y-auto mb-6 select-all">
          {summaryText}
        </div>

        {/* Actions */}
        <div className="flex items-center justify-end gap-3">
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2.5 rounded-xl text-xs font-bold text-slate-600 hover:bg-slate-100 transition-colors"
          >
            Close
          </button>

          <button
            type="button"
            onClick={handleCopy}
            className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl text-xs font-bold text-white bg-slate-900 hover:bg-brand-600 transition-all shadow-md active:scale-95"
          >
            {copied ? (
              <>
                <Check className="w-4 h-4 text-emerald-400" />
                <span>Copied to Clipboard!</span>
              </>
            ) : (
              <>
                <Copy className="w-4 h-4" />
                <span>Copy Summary</span>
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
};
